site_name: Hibby's Packet Radio Guide
site_url: https://packetradio.debian.net
nav:
  - Home: index.md
  - About: about.md
  - Beginner's Guide: beginners-guide.md
  - Radios: 
    - radios/index.md
  - Modems:
    - modems/ninotnc.md
    - modems/qtsm.md
    - modems/direwolf.md
  - Clients:
    - clients/qtttcp.md
  - Software Setup:
    - software.md
    - install/bpq.md
    - install/linux.md
  - Node Configuration:
    - config/bpq.md
    - config/linux.md
  - Misc:
    - repo.md
    - Glossary: glossary.md

theme: 
  name: readthedocs
  navigation_depth: 5
  collapse_navigation: false 
  sticky_navigation: true
  prev_next_buttons_location: none

plugins:
    - search

markdown_extensions:
  - toc:
      permalink: true
