site_name: Hibby's Packet Radio Guide
site_url: https://packetradio.debian.net
nav:
  - Home: "index.md"
  - About: "about.md"
  - Glossary: "glossary.md"
  - Radios: 
    - "radios/index.md"
  - Modems:
    - NinoTNC: "modems/ninotnc.md"
    - QtSoundModem: "modems/qtsm.md"
    - Direwolf: "modems/direwolf.md"
  - Clients:
    - QtTermTCP: "clients/qtttcp.md"
  - Software Setup:
    - "software.md"
    - BPQ: "install/bpq.md"
    - Linux: "install/linux.md"
  - Node Configuration:
    - BPQ: "config/bpq.md"
  - Misc:
    - Repo Setup: "repo.md"
theme: 
  name: readthedocs
  navigation_depth: 5
  collapse_navigation: False 
  sticky_navigation: False
  highlightjs: True
