site_name: Hibby's Packet Radio Guide
site_url: https://packetradio.debian.net
nav:
  - Home: index.md
  - About: about.md
  - Glossary: glossary.md
  - Radios: 
    - radios/index.md
  - Modems:
    - modems/ninotnc.md
    - modems/qtsm.md
    - modems/direwolf.md
  - Clients:
    - clients/qtttcp.md
  - Software Setup:
    - software.md
    - install/bpq.md
    - install/linux.md
  - Node Configuration:
    - config/bpq.md
  - Misc:
    - repo.md
theme: 
  name: readthedocs
  navigation_depth: 5
  collapse_navigation: False 
  sticky_navigation: True
  highlightjs: True
plugins:
    - search
